version: '2'
services:
    cli:
        build:
            context: ./
            dockerfile: ./cli.docker
        volumes:
            - ./:/code
        links:
            - "cache:cache_server"
            - "queue:queue_server"
    cache:
      image: memcached
      ports:
        - "127.0.0.1:11211:11211"
    queue:
      image: nickinchina/beanstalkd